# Generated by Django 2.1.2 on 2018-10-14 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181013_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='lala',
            new_name='imagen',
        ),
    ]
