# Generated by Django 2.1.2 on 2018-10-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181013_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
