# Generated by Django 2.1.2 on 2018-10-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181013_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
        migrations.AddField(
            model_name='post',
            name='imagenes',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
